#!/bin/bash

set -euo pipefail

# Build with specific Rust toolchain
docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/zohohorrorshow -w /usr/src/zohohorrorshow rust:1.39.0 cargo build --release